export const gymLeaders = [
  {
    number: 1,
    leader: "Falkner",
    city: "Violet City",
    specialty: "Flying",
    badge: "Zephyr",
    team: [
      {
        id: 1,
        name: "pidgey",
        level: 7,
        moves: ["tackle", "mud-slap"],
        types: ["normal", "flying"],
      },
      {
        id: 2,
        name: "pidgeotto",
        level: 9,
        moves: ["tackle", "mud-slap", "gust"],
        types: ["normal", "flying"],
      },
    ],
    rewards: {
      payout: 900,
      machine: "TM31 - Mud Slap",
    },
  },
  {
    number: 2,
    leader: "Bugsy",
    city: "Azalea Town",
    specialty: "Bug",
    badge: "Insect",
    team: [
      {
        id: 3,
        name: "metapod",
        level: 14,
        moves: ["tackle", "string shot", "harden"],
        types: ["bug"],
      },
      {
        id: 4,
        name: "kakuna",
        level: 14,
        moves: ["poison sting", "string shot", "harden"],
        types: ["bug", "poison"],
      },
      {
        id: 5,
        name: "scyther",
        level: 16,
        moves: ["quick attack", "leer", "fury cutter"],
        types: ["bug", "flying"],
      },
    ],
    rewards: {
      payout: 1600,
      machine: "TM49 - Fury Cutter",
    },
  },
  {
    number: 3,
    leader: "Whitney",
    city: "Goldenrod City",
    specialty: "Normal",
    badge: "Plain",
    team: [
      {
        id: 6,
        name: "clefairy",
        level: 18,
        moves: ["doubleslap", "mimic", "encore", "metronome"],
        types: ["normal"],
      },
      {
        id: 7,
        name: "miltank",
        level: 20,
        moves: ["rollout", "attract", "stomp", "milk drink"],
        types: ["normal"],
      },
    ],
    rewards: {
      payout: 2000,
      machine: "TM45 - Attract",
    },
  },
  {
    number: 4,
    leader: "Morty",
    city: "Ecruteak City",
    specialty: "Ghost",
    badge: "Fog",
    team: [
      {
        id: 8,
        name: "gastly",
        level: 21,
        moves: ["lick", "spite", "mean look", "curse"],
        types: ["ghost", "poison"],
      },
      {
        id: 9,
        name: "haunter",
        level: 21,
        moves: ["hypnosis", "mimic", "curse", "night shade"],
        types: ["ghost", "poison"],
      },
      {
        id: 10,
        name: "haunter",
        level: 23,
        moves: ["spite", "mean look", "mimic", "night shade"],
        types: ["ghost", "poison"],
      },
      {
        id: 11,
        name: "gengar",
        level: 25,
        moves: ["hypnosis", "shadow ball", "mean look", "dream eater"],
        types: ["ghost", "poison"],
      },
    ],
    rewards: {
      payout: 2300,
      machine: "TM34 - Shadow Ball",
    },
  },
  {
    number: 5,
    leader: "Chuck",
    city: "Cianwood City",
    specialty: "Fighting",
    badge: "Storm",
    team: [
      {
        id: 12,
        name: "primeape",
        level: 27,
        moves: ["leer", "rage", "karate chop", "fury swipes"],
        types: ["fight"],
      },
      {
        id: 13,
        name: "poliwrath",
        level: 30,
        moves: ["hypnosis", "mind reader", "surf", "dynamicpunch"],
        types: ["fight", "water"],
      },
    ],
    rewards: {
      payout: 3000,
      machine: "TM01 - Dynamic Punch",
    },
  },
  {
    number: 6,
    leader: "Jasmine",
    city: "Olivine City",
    specialty: "Steel",
    badge: "Mineral",
    team: [
      {
        id: 14,
        name: "magnemite",
        level: 30,
        moves: ["thunderbolt", "supersonic", "sonicboom", "thunder wave"],
        types: ["electric", "steel"],
      },
      {
        id: 15,
        name: "magnemite",
        level: 30,
        moves: ["thunderbolt", "supersonic", "sonicboom", "thunder wave"],
        types: ["electric", "steel"],
      },
      {
        id: 16,
        name: "steelix",
        level: 35,
        moves: ["screech", "sunny day", "rock throw", "iron tail"],
        types: ["ground", "steel"],
      },
    ],
    rewards: {
      payout: 3500,
      machine: "TM23 - Iron Tail",
    },
  },
  {
    number: 7,
    leader: "Pryce",
    city: "Mahogany Town",
    specialty: "Ice",
    badge: "Glacier",
    team: [
      {
        id: 17,
        name: "seel",
        level: 27,
        moves: ["headbutt", "icy wind", "aurora beam", "rest"],
        types: ["water"],
      },
      {
        id: 18,
        name: "dewgong",
        level: 29,
        moves: ["headbutt", "icy wind", "aurora beam", "rest"],
        types: ["water", "ice"],
      },
      {
        id: 19,
        name: "piloswine",
        level: 31,
        moves: ["icy wind", "fury attack", "mist", "blizzard"],
        types: ["ice", "ground"],
      },
    ],
    rewards: {
      payout: 3100,
      machine: "TM16 - Icy Wind",
    },
  },
  {
    number: 8,
    leader: "Clair",
    city: "Blackthorn City",
    specialty: "Dragon",
    badge: "Rising",
    team: [
      {
        id: 20,
        name: "dragonair",
        level: 37,
        moves: ["thunder wave", "surf", "slam", "dragonbreath"],
        types: ["dragon"],
      },
      {
        id: 21,
        name: "dragonair",
        level: 37,
        moves: ["thunder wave", "thunderbolt", "slam", "dragonbreath"],
        types: ["dragon"],
      },
      {
        id: 22,
        name: "dragonair",
        level: 37,
        moves: ["thunder wave", "ice beam", "slam", "dragonbreath"],
        types: ["dragon"],
      },
      {
        id: 23,
        name: "kingdra",
        level: 40,
        moves: ["smokescreen", "surf", "hyper beam", "dragonbreath"],
        types: ["water", "dragon"],
      },
    ],
    rewards: {
      payout: 4000,
      machine: "TM24 - Dragons Breath",
    },
  },
];
